/* generated by stasc 1.3 */
Table=function(){
	var n0=document.createElementNS('http://www.w3.org/2000/svg','svg');
	n0.setAttribute('width','320');
	n0.setAttribute('height','480');
	var n1=document.createElementNS('http://www.w3.org/2000/svg','rect');
	n1.setAttribute('x','0');
	n1.setAttribute('y','0');
	n1.setAttribute('fill','black');
	n1.setAttribute('width','320');
	n1.setAttribute('height','480');
	n0.appendChild(n1);
	var n2=document.createElementNS('http://www.w3.org/2000/svg','rect');
	n2.setAttribute('x','5');
	n2.setAttribute('y','5');
	n2.setAttribute('fill','royalblue');
	n2.setAttribute('width','310');
	n2.setAttribute('height','470');
	n0.appendChild(n2);
	var n3=document.createElementNS('http://www.w3.org/2000/svg','rect');
	n3.setAttribute('x','100');
	n3.setAttribute('y','0');
	n3.setAttribute('fill','royalblue');
	n3.setAttribute('width','120');
	n3.setAttribute('height','480');
	n0.appendChild(n3);
	return n0;
};
