/* generated by stasc 1.5 */
Clear=function(){
	var n0=document.createElementNS('http://www.w3.org/2000/svg','g');
	return n0;
};
End=function(){
	var n0=document.createElementNS('http://www.w3.org/2000/svg','g');
	var n1=document.createElementNS('http://www.w3.org/2000/svg','text');
	n1.setAttribute('x','160');
	n1.setAttribute('y','240');
	n1.setAttribute('text-anchor','middle');
	n1.setAttribute('font-size','28');
	n1.setAttribute('font-family','Helvetica');
	n1.setAttribute('fill','white');
	n1.appendChild(document.createTextNode('Game Over'));
	n0.appendChild(n1);
	var n2=document.createElementNS('http://www.w3.org/2000/svg','text');
	n2.setAttribute('x','160');
	n2.setAttribute('y','260');
	n2.setAttribute('text-anchor','end');
	n2.setAttribute('font-size','14');
	n2.setAttribute('font-family','Helvetica');
	n2.setAttribute('fill','white');
	n2.appendChild(document.createTextNode('All Time Best:'));
	n0.appendChild(n2);
	var n3=document.createElementNS('http://www.w3.org/2000/svg','text');
	n3.setAttribute('x','160');
	n3.setAttribute('y','260');
	n3.setAttribute('text-anchor','start');
	n3.setAttribute('font-size','14');
	n3.setAttribute('font-family','Helvetica');
	n3.setAttribute('fill','white');
	Object.defineProperty(n0, 'AlltimeBest',{
		set:function(v){n3.textContent=v;},
		get:function(){return n3.textContent;}
	});
	n0.appendChild(n3);
	var n4=document.createElementNS('http://www.w3.org/2000/svg','text');
	n4.setAttribute('x','160');
	n4.setAttribute('y','280');
	n4.setAttribute('text-anchor','end');
	n4.setAttribute('font-size','14');
	n4.setAttribute('font-family','Helvetica');
	n4.setAttribute('fill','white');
	n4.appendChild(document.createTextNode('Today\'s Best:'));
	n0.appendChild(n4);
	var n5=document.createElementNS('http://www.w3.org/2000/svg','text');
	n5.setAttribute('x','160');
	n5.setAttribute('y','280');
	n5.setAttribute('text-anchor','start');
	n5.setAttribute('font-size','14');
	n5.setAttribute('font-family','Helvetica');
	n5.setAttribute('fill','white');
	Object.defineProperty(n0, 'TodaysBest',{
		set:function(v){n5.textContent=v;},
		get:function(){return n5.textContent;}
	});
	n0.appendChild(n5);
	var n6=document.createElementNS('http://www.w3.org/2000/svg','text');
	n6.setAttribute('x','160');
	n6.setAttribute('y','300');
	n6.setAttribute('text-anchor','middle');
	n6.setAttribute('font-size','14');
	n6.setAttribute('font-family','Helvetica');
	n6.setAttribute('fill','White');
	n6.setAttribute('text-decoration','underline');
	n6.setAttribute('style','cursor:pointer;');
	n6.setAttribute('onclick','start();');
	n6.appendChild(document.createTextNode('Replay'));
	n0.appendChild(n6);
	return n0;
};
Orange=function(){
	var n0=document.createElementNS('http://www.w3.org/2000/svg','g');
	var mX='0';
	if(0<arguments.length){
		mX=arguments[0];
	}
	Object.defineProperty(n0, 'X',{
		set:function(v){mX=v;n0.setAttribute('transform','translate('+mX+' '+mY+')');},
		get:function(){return mX;}
	});
	var mY='0';
	if(1<arguments.length){
		mY=arguments[1];
	}
	Object.defineProperty(n0, 'Y',{
		set:function(v){mY=v;n0.setAttribute('transform','translate('+mX+' '+mY+')');},
		get:function(){return mY;}
	});
	n0.setAttribute('transform','translate('+mX+' '+mY+')');
	var n1=document.createElementNS('http://www.w3.org/2000/svg','g');
	Object.defineProperty(n0, 'Opacity',{
		set:function(v){n1.setAttribute('opacity',v);},
		get:function(){return n1.getAttribute('opacity');}
	});
	var n2=document.createElementNS('http://www.w3.org/2000/svg','circle');
	n2.setAttribute('fill','#FF7F00');
	n2.setAttribute('stroke','none');
	n2.setAttribute('cx','0');
	n2.setAttribute('cy','0');
	n2.setAttribute('r','10');
	n2.setAttribute('opacity','1');
	Object.defineProperty(n0, 'R',{
		set:function(v){n2.setAttribute('r',v);},
		get:function(){return n2.getAttribute('r');}
	});
	n1.appendChild(n2);
	var n3=document.createElementNS('http://www.w3.org/2000/svg','line');
	n3.setAttribute('x1','0');
	n3.setAttribute('y1','-7');
	n3.setAttribute('x2','0');
	n3.setAttribute('y2','7');
	n3.setAttribute('stroke','black');
	n3.setAttribute('stroke-width','4');
	n1.appendChild(n3);
	var n4=document.createElementNS('http://www.w3.org/2000/svg','line');
	n4.setAttribute('x1','-7');
	n4.setAttribute('y1','0');
	n4.setAttribute('x2','7');
	n4.setAttribute('y2','0');
	n4.setAttribute('stroke','black');
	n4.setAttribute('stroke-width','4');
	n1.appendChild(n4);
	n0.appendChild(n1);
	var n5=document.createElementNS('http://www.w3.org/2000/svg','text');
	n5.setAttribute('x','0');
	n5.setAttribute('y','0');
	n5.setAttribute('text-anchor','middle');
	n5.setAttribute('font-size','12');
	n5.setAttribute('font-family','Monospace');
	n5.setAttribute('fill','white');
	Object.defineProperty(n0, 'Text',{
		set:function(v){n5.textContent=v;},
		get:function(){return n5.textContent;}
	});
	n0.appendChild(n5);
	return n0;
};
Red=function(){
	var n0=document.createElementNS('http://www.w3.org/2000/svg','g');
	var mX='0';
	if(0<arguments.length){
		mX=arguments[0];
	}
	Object.defineProperty(n0, 'X',{
		set:function(v){mX=v;n0.setAttribute('transform','translate('+mX+' '+mY+')');},
		get:function(){return mX;}
	});
	var mY='0';
	if(1<arguments.length){
		mY=arguments[1];
	}
	Object.defineProperty(n0, 'Y',{
		set:function(v){mY=v;n0.setAttribute('transform','translate('+mX+' '+mY+')');},
		get:function(){return mY;}
	});
	n0.setAttribute('transform','translate('+mX+' '+mY+')');
	var n1=document.createElementNS('http://www.w3.org/2000/svg','g');
	Object.defineProperty(n0, 'Opacity',{
		set:function(v){n1.setAttribute('opacity',v);},
		get:function(){return n1.getAttribute('opacity');}
	});
	var n2=document.createElementNS('http://www.w3.org/2000/svg','circle');
	n2.setAttribute('fill','#FF0000');
	n2.setAttribute('stroke','none');
	n2.setAttribute('cx','0');
	n2.setAttribute('cy','0');
	n2.setAttribute('r','10');
	n2.setAttribute('opacity','1');
	Object.defineProperty(n0, 'R',{
		set:function(v){n2.setAttribute('r',v);},
		get:function(){return n2.getAttribute('r');}
	});
	n1.appendChild(n2);
	var n3=document.createElementNS('http://www.w3.org/2000/svg','line');
	n3.setAttribute('x1','-6');
	n3.setAttribute('y1','-4');
	n3.setAttribute('x2','6');
	n3.setAttribute('y2','-4');
	n3.setAttribute('stroke','black');
	n3.setAttribute('stroke-width','4');
	n1.appendChild(n3);
	var n4=document.createElementNS('http://www.w3.org/2000/svg','line');
	n4.setAttribute('x1','-6');
	n4.setAttribute('y1','4');
	n4.setAttribute('x2','6');
	n4.setAttribute('y2','4');
	n4.setAttribute('stroke','black');
	n4.setAttribute('stroke-width','4');
	n1.appendChild(n4);
	n0.appendChild(n1);
	var n5=document.createElementNS('http://www.w3.org/2000/svg','text');
	n5.setAttribute('x','0');
	n5.setAttribute('y','0');
	n5.setAttribute('text-anchor','middle');
	n5.setAttribute('font-size','12');
	n5.setAttribute('font-family','Monospace');
	n5.setAttribute('fill','white');
	Object.defineProperty(n0, 'Text',{
		set:function(v){n5.textContent=v;},
		get:function(){return n5.textContent;}
	});
	n0.appendChild(n5);
	return n0;
};
Screen=function(){
	var n0=document.createElementNS('http://www.w3.org/2000/svg','svg');
	n0.setAttribute('width','320');
	n0.setAttribute('height','460');
	n0.setAttribute('viewBox','0 0 320 460');
	n0.setAttribute('viewPort','0 0 320 460');
	n0.setAttribute('style','margin: 0; padding: 0;');
	Object.defineProperty(n0, 'Position',{
		set:function(v){n0.style.position=v;},
		get:function(){return n0.style.position;}
	});
	Object.defineProperty(n0, 'Left',{
		set:function(v){n0.style.left=v;},
		get:function(){return n0.style.left;}
	});
	Object.defineProperty(n0, 'Top',{
		set:function(v){n0.style.top=v;},
		get:function(){return n0.style.top;}
	});
	Object.defineProperty(n0, 'Width',{
		set:function(v){n0.setAttribute('width',v);},
		get:function(){return n0.getAttribute('width');}
	});
	Object.defineProperty(n0, 'Height',{
		set:function(v){n0.setAttribute('height',v);},
		get:function(){return n0.getAttribute('height');}
	});
	var n1=document.createElementNS('http://www.w3.org/2000/svg','rect');
	n1.setAttribute('x','0');
	n1.setAttribute('y','0');
	n1.setAttribute('fill','black');
	n1.setAttribute('width','320');
	n1.setAttribute('height','460');
	n0.appendChild(n1);
	var n2=document.createElementNS('http://www.w3.org/2000/svg','circle');
	n2.setAttribute('visibility','hidden');
	n2.setAttribute('fill','white');
	n2.setAttribute('cx','160');
	n2.setAttribute('cy','240');
	n2.setAttribute('r','10');
	Object.defineProperty(n0, 'PuckVisibility',{
		set:function(v){n2.setAttribute('visibility',v);},
		get:function(){return n2.getAttribute('visibility');}
	});
	Object.defineProperty(n0, 'PuckX',{
		set:function(v){n2.setAttribute('cx',v);},
		get:function(){return n2.getAttribute('cx');}
	});
	Object.defineProperty(n0, 'PuckY',{
		set:function(v){n2.setAttribute('cy',v);},
		get:function(){return n2.getAttribute('cy');}
	});
	n0.appendChild(n2);
	var n3=document.createElementNS('http://www.w3.org/2000/svg','circle');
	n3.setAttribute('fill','lightgrey');
	n3.setAttribute('cx','160');
	n3.setAttribute('cy','430');
	n3.setAttribute('r','50');
	Object.defineProperty(n0, 'YouX',{
		set:function(v){n3.setAttribute('cx',v);},
		get:function(){return n3.getAttribute('cx');}
	});
	n0.appendChild(n3);
	var n4=document.createElementNS('http://www.w3.org/2000/svg','rect');
	n4.setAttribute('x','0');
	n4.setAttribute('y','430');
	n4.setAttribute('fill','black');
	n4.setAttribute('width','320');
	n4.setAttribute('height','30');
	n0.appendChild(n4);
	var n5=document.createElementNS('http://www.w3.org/2000/svg','g');
	Object.defineProperty(n0,'Stage',{
		set:function(v){n0.replaceChild(v,n5);n5=v;},
		get:function(){return n5;}
	});
	n0.appendChild(n5);
	var n6=document.createElementNS('http://www.w3.org/2000/svg','g');
	var n7=document.createElementNS('http://www.w3.org/2000/svg','text');
	n7.setAttribute('x','160');
	n7.setAttribute('y','260');
	n7.setAttribute('text-anchor','end');
	n7.setAttribute('font-size','14');
	n7.setAttribute('font-family','Helvetica');
	n7.setAttribute('fill','white');
	n7.appendChild(document.createTextNode('All Time Best:'));
	n6.appendChild(n7);
	var n8=document.createElementNS('http://www.w3.org/2000/svg','text');
	n8.setAttribute('x','160');
	n8.setAttribute('y','260');
	n8.setAttribute('text-anchor','start');
	n8.setAttribute('font-size','14');
	n8.setAttribute('font-family','Helvetica');
	n8.setAttribute('fill','white');
	Object.defineProperty(n6, 'AlltimeBest',{
		set:function(v){n8.textContent=v;},
		get:function(){return n8.textContent;}
	});
	n6.appendChild(n8);
	var n9=document.createElementNS('http://www.w3.org/2000/svg','text');
	n9.setAttribute('x','160');
	n9.setAttribute('y','280');
	n9.setAttribute('text-anchor','end');
	n9.setAttribute('font-size','14');
	n9.setAttribute('font-family','Helvetica');
	n9.setAttribute('fill','white');
	n9.appendChild(document.createTextNode('Today\'s Best:'));
	n6.appendChild(n9);
	var n10=document.createElementNS('http://www.w3.org/2000/svg','text');
	n10.setAttribute('x','160');
	n10.setAttribute('y','280');
	n10.setAttribute('text-anchor','start');
	n10.setAttribute('font-size','14');
	n10.setAttribute('font-family','Helvetica');
	n10.setAttribute('fill','white');
	Object.defineProperty(n6, 'TodaysBest',{
		set:function(v){n10.textContent=v;},
		get:function(){return n10.textContent;}
	});
	n6.appendChild(n10);
	var n11=document.createElementNS('http://www.w3.org/2000/svg','text');
	n11.setAttribute('x','160');
	n11.setAttribute('y','300');
	n11.setAttribute('text-anchor','middle');
	n11.setAttribute('font-size','14');
	n11.setAttribute('font-family','Helvetica');
	n11.setAttribute('fill','white');
	n11.setAttribute('text-decoration','underline');
	n11.setAttribute('style','cursor:pointer;');
	n11.setAttribute('onclick','start();');
	n11.appendChild(document.createTextNode('Start'));
	n6.appendChild(n11);
	Object.defineProperty(n0,'Title',{
		set:function(v){n0.replaceChild(v,n6);n6=v;},
		get:function(){return n6;}
	});
	n0.appendChild(n6);
	var n12=document.createElementNS('http://www.w3.org/2000/svg','text');
	n12.setAttribute('x','320');
	n12.setAttribute('y','20');
	n12.setAttribute('text-anchor','end');
	n12.setAttribute('font-size','18');
	n12.setAttribute('font-family','Monospace');
	n12.setAttribute('fill','white');
	Object.defineProperty(n0, 'Score',{
		set:function(v){n12.textContent=v;},
		get:function(){return n12.textContent;}
	});
	n0.appendChild(n12);
	var n13=document.createElementNS('http://www.w3.org/2000/svg','text');
	n13.setAttribute('x','0');
	n13.setAttribute('y','20');
	n13.setAttribute('text-anchor','start');
	n13.setAttribute('font-size','18');
	n13.setAttribute('font-family','Monospace');
	n13.setAttribute('fill','white');
	Object.defineProperty(n0, 'Time',{
		set:function(v){n13.textContent=v;},
		get:function(){return n13.textContent;}
	});
	n0.appendChild(n13);
	return n0;
};
Stage=function(){
	var n0=document.createElementNS('http://www.w3.org/2000/svg','g');
	var n1=document.createElementNS('http://www.w3.org/2000/svg','text');
	n1.setAttribute('x','0');
	n1.setAttribute('y','450');
	n1.setAttribute('text-anchor','start');
	n1.setAttribute('font-size','24');
	n1.setAttribute('font-family','Helvetica');
	n1.setAttribute('fill','white');
	n1.appendChild(document.createTextNode('Paraboloid'));
	n0.appendChild(n1);
	var n2=document.createElementNS('http://www.w3.org/2000/svg','text');
	n2.setAttribute('x','320');
	n2.setAttribute('y','450');
	n2.setAttribute('text-anchor','end');
	n2.setAttribute('font-size','24');
	n2.setAttribute('font-family','Helvetica');
	n2.setAttribute('fill','white');
	Object.defineProperty(n0, 'Text',{
		set:function(v){n2.textContent=v;},
		get:function(){return n2.textContent;}
	});
	if(0<arguments.length){
		n0.Text=arguments[0];
	}
	n0.appendChild(n2);
	return n0;
};
Yellow=function(){
	var n0=document.createElementNS('http://www.w3.org/2000/svg','g');
	var mX='0';
	if(0<arguments.length){
		mX=arguments[0];
	}
	Object.defineProperty(n0, 'X',{
		set:function(v){mX=v;n0.setAttribute('transform','translate('+mX+' '+mY+')');},
		get:function(){return mX;}
	});
	var mY='0';
	if(1<arguments.length){
		mY=arguments[1];
	}
	Object.defineProperty(n0, 'Y',{
		set:function(v){mY=v;n0.setAttribute('transform','translate('+mX+' '+mY+')');},
		get:function(){return mY;}
	});
	n0.setAttribute('transform','translate('+mX+' '+mY+')');
	var n1=document.createElementNS('http://www.w3.org/2000/svg','g');
	Object.defineProperty(n0, 'Opacity',{
		set:function(v){n1.setAttribute('opacity',v);},
		get:function(){return n1.getAttribute('opacity');}
	});
	var n2=document.createElementNS('http://www.w3.org/2000/svg','circle');
	n2.setAttribute('fill','#FFFF00');
	n2.setAttribute('stroke','none');
	n2.setAttribute('cx','0');
	n2.setAttribute('cy','0');
	n2.setAttribute('r','10');
	n2.setAttribute('opacity','1');
	Object.defineProperty(n0, 'R',{
		set:function(v){n2.setAttribute('r',v);},
		get:function(){return n2.getAttribute('r');}
	});
	n1.appendChild(n2);
	var n3=document.createElementNS('http://www.w3.org/2000/svg','line');
	n3.setAttribute('x1','-5');
	n3.setAttribute('y1','-5');
	n3.setAttribute('x2','5');
	n3.setAttribute('y2','5');
	n3.setAttribute('stroke','black');
	n3.setAttribute('stroke-width','4');
	n1.appendChild(n3);
	var n4=document.createElementNS('http://www.w3.org/2000/svg','line');
	n4.setAttribute('x1','5');
	n4.setAttribute('y1','-5');
	n4.setAttribute('x2','-5');
	n4.setAttribute('y2','5');
	n4.setAttribute('stroke','black');
	n4.setAttribute('stroke-width','4');
	n1.appendChild(n4);
	n0.appendChild(n1);
	var n5=document.createElementNS('http://www.w3.org/2000/svg','text');
	n5.setAttribute('x','0');
	n5.setAttribute('y','0');
	n5.setAttribute('text-anchor','middle');
	n5.setAttribute('font-size','12');
	n5.setAttribute('font-family','Monospace');
	n5.setAttribute('fill','white');
	Object.defineProperty(n0, 'Text',{
		set:function(v){n5.textContent=v;},
		get:function(){return n5.textContent;}
	});
	n0.appendChild(n5);
	return n0;
};
