/* generated by stasc 1.5 */
Clear=function(){
	var n0=document.createElementNS('http://www.w3.org/2000/svg','g');
	return n0;
};
End=function(){
	var n0=document.createElementNS('http://www.w3.org/2000/svg','g');
	var n1=document.createElementNS('http://www.w3.org/2000/svg','g');
	n1.setAttribute('transform','translate(265, 180) scale(-1, 1)');
	Object.defineProperty(n0,'Lost',{
		get:function(){return n1;}
	});
	n0.appendChild(n1);
	var n2=document.createElementNS('http://www.w3.org/2000/svg','text');
	n2.setAttribute('x','160');
	n2.setAttribute('y','220');
	n2.setAttribute('text-anchor','middle');
	n2.setAttribute('font-size','14');
	n2.setAttribute('fill','white');
	n2.appendChild(document.createTextNode('Game Over'));
	n0.appendChild(n2);
	var n3=document.createElementNS('http://www.w3.org/2000/svg','text');
	n3.setAttribute('x','160');
	n3.setAttribute('y','250');
	n3.setAttribute('text-anchor','middle');
	n3.setAttribute('font-size','32');
	n3.setAttribute('fill','White');
	Object.defineProperty(n0, 'Numbers',{
		set:function(v){n3.textContent=v;},
		get:function(){return n3.textContent;}
	});
	if(0<arguments.length){
		n0.Numbers=arguments[0];
	}
	n0.appendChild(n3);
	var n4=document.createElementNS('http://www.w3.org/2000/svg','text');
	n4.setAttribute('x','160');
	n4.setAttribute('y','270');
	n4.setAttribute('text-anchor','middle');
	n4.setAttribute('font-size','14');
	n4.setAttribute('fill','White');
	n4.setAttribute('text-decoration','underline');
	n4.setAttribute('style','cursor:pointer;');
	n4.setAttribute('onclick','start();');
	n4.appendChild(document.createTextNode('Replay'));
	n0.appendChild(n4);
	var n5=document.createElementNS('http://www.w3.org/2000/svg','g');
	n5.setAttribute('transform','translate(55, 300)');
	Object.defineProperty(n0,'Got',{
		get:function(){return n5;}
	});
	n0.appendChild(n5);
	return n0;
};
Off=function(){
	var n0=document.createElementNS('http://www.w3.org/2000/svg','g');
	var n1=document.createElementNS('http://www.w3.org/2000/svg','circle');
	n1.setAttribute('stroke','black');
	n1.setAttribute('fill','none');
	n1.setAttribute('cy','0');
	n1.setAttribute('r','15');
	Object.defineProperty(n0, 'X',{
		set:function(v){n1.setAttribute('cx',v);},
		get:function(){return n1.getAttribute('cx');}
	});
	if(0<arguments.length){
		n0.X=arguments[0];
	}
	n0.appendChild(n1);
	return n0;
};
On=function(){
	var n0=document.createElementNS('http://www.w3.org/2000/svg','g');
	var n1=document.createElementNS('http://www.w3.org/2000/svg','circle');
	n1.setAttribute('stroke','black');
	n1.setAttribute('fill','yellow');
	n1.setAttribute('cy','0');
	n1.setAttribute('r','15');
	Object.defineProperty(n0, 'X',{
		set:function(v){n1.setAttribute('cx',v);},
		get:function(){return n1.getAttribute('cx');}
	});
	if(0<arguments.length){
		n0.X=arguments[0];
	}
	n0.appendChild(n1);
	return n0;
};
Score=function(){
	var n0=document.createElementNS('http://www.w3.org/2000/svg','g');
	var n1=document.createElementNS('http://www.w3.org/2000/svg','g');
	n1.setAttribute('transform','translate(265, 180) scale(-1, 1)');
	Object.defineProperty(n0,'Lost',{
		get:function(){return n1;}
	});
	n0.appendChild(n1);
	var n2=document.createElementNS('http://www.w3.org/2000/svg','text');
	n2.setAttribute('x','160');
	n2.setAttribute('y','250');
	n2.setAttribute('text-anchor','middle');
	n2.setAttribute('font-size','32');
	n2.setAttribute('fill','white');
	Object.defineProperty(n0, 'Numbers',{
		set:function(v){n2.textContent=v;},
		get:function(){return n2.textContent;}
	});
	if(0<arguments.length){
		n0.Numbers=arguments[0];
	}
	n0.appendChild(n2);
	var n3=document.createElementNS('http://www.w3.org/2000/svg','g');
	n3.setAttribute('transform','translate(55, 300)');
	Object.defineProperty(n0,'Got',{
		get:function(){return n3;}
	});
	n0.appendChild(n3);
	return n0;
};
Table=function(){
	var n0=document.createElementNS('http://www.w3.org/2000/svg','svg');
	n0.setAttribute('width','320');
	n0.setAttribute('height','480');
	var n1=document.createElementNS('http://www.w3.org/2000/svg','rect');
	n1.setAttribute('x','0');
	n1.setAttribute('y','0');
	n1.setAttribute('fill','black');
	n1.setAttribute('width','320');
	n1.setAttribute('height','480');
	n0.appendChild(n1);
	var n2=document.createElementNS('http://www.w3.org/2000/svg','rect');
	n2.setAttribute('x','5');
	n2.setAttribute('y','5');
	n2.setAttribute('fill','royalblue');
	n2.setAttribute('width','310');
	n2.setAttribute('height','470');
	n0.appendChild(n2);
	var n3=document.createElementNS('http://www.w3.org/2000/svg','rect');
	n3.setAttribute('x','100');
	n3.setAttribute('y','0');
	n3.setAttribute('fill','royalblue');
	n3.setAttribute('width','120');
	n3.setAttribute('height','480');
	n0.appendChild(n3);
	var n4=document.createElementNS('http://www.w3.org/2000/svg','g');
	var mFoeX='160';
	Object.defineProperty(n0, 'FoeX',{
		set:function(v){mFoeX=v;n4.setAttribute('transform','translate('+mFoeX+' 80)');},
		get:function(){return mFoeX;}
	});
	n4.setAttribute('transform','translate('+mFoeX+' 80)');
	var n5=document.createElementNS('http://www.w3.org/2000/svg','circle');
	n5.setAttribute('fill','lightgrey');
	n5.setAttribute('stroke','black');
	n5.setAttribute('cx','0');
	n5.setAttribute('cy','0');
	n5.setAttribute('r','25');
	n4.appendChild(n5);
	var n6=document.createElementNS('http://www.w3.org/2000/svg','circle');
	n6.setAttribute('fill','lightgrey');
	n6.setAttribute('stroke','black');
	n6.setAttribute('cx','0');
	n6.setAttribute('cy','0');
	n6.setAttribute('r','12');
	n4.appendChild(n6);
	n0.appendChild(n4);
	var n7=document.createElementNS('http://www.w3.org/2000/svg','circle');
	n7.setAttribute('visibility','hidden');
	n7.setAttribute('fill','yellow');
	n7.setAttribute('stroke','black');
	n7.setAttribute('cx','160');
	n7.setAttribute('cy','240');
	n7.setAttribute('r','20');
	Object.defineProperty(n0, 'PuckVisibility',{
		set:function(v){n7.setAttribute('visibility',v);},
		get:function(){return n7.getAttribute('visibility');}
	});
	Object.defineProperty(n0, 'PuckX',{
		set:function(v){n7.setAttribute('cx',v);},
		get:function(){return n7.getAttribute('cx');}
	});
	Object.defineProperty(n0, 'PuckY',{
		set:function(v){n7.setAttribute('cy',v);},
		get:function(){return n7.getAttribute('cy');}
	});
	n0.appendChild(n7);
	var n8=document.createElementNS('http://www.w3.org/2000/svg','g');
	var mYouX='160';
	Object.defineProperty(n0, 'YouX',{
		set:function(v){mYouX=v;n8.setAttribute('transform','translate('+mYouX+' 400)');},
		get:function(){return mYouX;}
	});
	n8.setAttribute('transform','translate('+mYouX+' 400)');
	var n9=document.createElementNS('http://www.w3.org/2000/svg','circle');
	n9.setAttribute('fill','lightgrey');
	n9.setAttribute('stroke','black');
	n9.setAttribute('cx','0');
	n9.setAttribute('cy','0');
	n9.setAttribute('r','25');
	n8.appendChild(n9);
	var n10=document.createElementNS('http://www.w3.org/2000/svg','circle');
	n10.setAttribute('fill','lightgrey');
	n10.setAttribute('stroke','black');
	n10.setAttribute('cx','0');
	n10.setAttribute('cy','0');
	n10.setAttribute('r','12');
	n8.appendChild(n10);
	n0.appendChild(n8);
	var n11=document.createElementNS('http://www.w3.org/2000/svg','g');
	var n12=document.createElementNS('http://www.w3.org/2000/svg','text');
	n12.setAttribute('x','160');
	n12.setAttribute('y','240');
	n12.setAttribute('text-anchor','middle');
	n12.setAttribute('font-size','28');
	n12.setAttribute('fill','white');
	n12.appendChild(document.createTextNode('SVGAirHockey'));
	n11.appendChild(n12);
	var n13=document.createElementNS('http://www.w3.org/2000/svg','text');
	n13.setAttribute('x','160');
	n13.setAttribute('y','260');
	n13.setAttribute('text-anchor','middle');
	n13.setAttribute('font-size','14');
	n13.setAttribute('fill','white');
	n13.setAttribute('text-decoration','underline');
	n13.setAttribute('style','cursor:pointer;');
	n13.setAttribute('onclick','start();');
	n13.appendChild(document.createTextNode('Start'));
	n11.appendChild(n13);
	Object.defineProperty(n0,'Overlay',{
		set:function(v){n0.replaceChild(v,n11);n11=v;},
		get:function(){return n11;}
	});
	n0.appendChild(n11);
	return n0;
};
